// Core Configuration
export { defineConfig, getConfig, type CartinoUIConfig, defineTheme, getTheme, setTheme } from './config.js'
export type { ThemeConfig, ComponentTheme, IconConfig, ColorMapping, ThemePreset } from './config.js'

// Theme System
export { useTheme, useThemeConfig, mergeTheme, getDefaultTheme, getDefaultIcons, THEME_CONFIG_KEY } from './runtime/composables/useTheme.js'
export { useAppConfig, useUIConfig, useColors, useIcons, createAppConfig, APP_CONFIG_KEY, type AppConfig } from './runtime/composables/useAppConfig.js'
export { useUI, useUISlots, mergeUIClasses, getSlotClass, type UseUIOptions, type WithUIProps } from './runtime/composables/useUI.js'
export { default as ThemeProvider } from './runtime/components/ThemeProvider.vue'

// Theme Presets
export { presets, getPreset, listPresets, defaultPreset, minimalPreset, modernPreset } from './presets/index.js'

// Components (kebab-case: ui-accordion, ui-alert, ui-app, etc.)
export { default as UiAccordion } from './runtime/components/Accordion.vue'
export { default as UiAlert } from './runtime/components/Alert.vue'
export { default as UiApp } from './runtime/components/App.vue'
export { default as UiAuthForm } from './runtime/components/AuthForm.vue'
export { default as UiAvatar } from './runtime/components/Avatar.vue'
export { default as UiAvatarGroup } from './runtime/components/AvatarGroup.vue'
export { default as UiBadge } from './runtime/components/Badge.vue'
export { default as UiBanner } from './runtime/components/Banner.vue'
export { default as UiBlogPost } from './runtime/components/BlogPost.vue'
export { default as UiBlogPosts } from './runtime/components/BlogPosts.vue'
export { default as UiBreadcrumb } from './runtime/components/Breadcrumb.vue'
export { default as UiButton } from './runtime/components/Button.vue'
export { default as UiCalendar } from './runtime/components/Calendar.vue'
export { default as UiCard } from './runtime/components/Card.vue'
export { default as UiCarousel } from './runtime/components/Carousel.vue'
export { default as UiChangelogVersion } from './runtime/components/ChangelogVersion.vue'
export { default as UiChangelogVersions } from './runtime/components/ChangelogVersions.vue'
export { default as UiChatMessage } from './runtime/components/ChatMessage.vue'
export { default as UiChatMessages } from './runtime/components/ChatMessages.vue'
export { default as UiChatPalette } from './runtime/components/ChatPalette.vue'
export { default as UiChatPrompt } from './runtime/components/ChatPrompt.vue'
export { default as UiChatPromptSubmit } from './runtime/components/ChatPromptSubmit.vue'
export { default as UiCheckbox } from './runtime/components/Checkbox.vue'
export { default as UiCheckboxGroup } from './runtime/components/CheckboxGroup.vue'
export { default as UiChip } from './runtime/components/Chip.vue'
export { default as UiCollapsible } from './runtime/components/Collapsible.vue'
export { default as UiColorPicker } from './runtime/components/ColorPicker.vue'
export { default as UiCommandPalette } from './runtime/components/CommandPalette.vue'
export { default as UiContainer } from './runtime/components/Container.vue'
export { default as UiContextMenu } from './runtime/components/ContextMenu.vue'
export { default as UiContextMenuContent } from './runtime/components/ContextMenuContent.vue'
export { default as UiDashboardGroup } from './runtime/components/DashboardGroup.vue'
export { default as UiDashboardNavbar } from './runtime/components/DashboardNavbar.vue'
export { default as UiDashboardPanel } from './runtime/components/DashboardPanel.vue'
export { default as UiDashboardResizeHandle } from './runtime/components/DashboardResizeHandle.vue'
export { default as UiDashboardSearch } from './runtime/components/DashboardSearch.vue'
export { default as UiDashboardSearchButton } from './runtime/components/DashboardSearchButton.vue'
export { default as UiDashboardSidebar } from './runtime/components/DashboardSidebar.vue'
export { default as UiDashboardSidebarCollapse } from './runtime/components/DashboardSidebarCollapse.vue'
export { default as UiDashboardSidebarToggle } from './runtime/components/DashboardSidebarToggle.vue'
export { default as UiDashboardToolbar } from './runtime/components/DashboardToolbar.vue'
export { default as UiDrawer } from './runtime/components/Drawer.vue'
export { default as UiDropdownMenu } from './runtime/components/DropdownMenu.vue'
export { default as UiDropdownMenuContent } from './runtime/components/DropdownMenuContent.vue'
export { default as UiEmpty } from './runtime/components/Empty.vue'
export { default as UiError } from './runtime/components/Error.vue'
export { default as UiFieldGroup } from './runtime/components/FieldGroup.vue'
export { default as UiFileUpload } from './runtime/components/FileUpload.vue'
export { default as UiFooter } from './runtime/components/Footer.vue'
export { default as UiFooterColumns } from './runtime/components/FooterColumns.vue'
export { default as UiForm } from './runtime/components/Form.vue'
export { default as UiFormField } from './runtime/components/FormField.vue'
export { default as UiHeader } from './runtime/components/Header.vue'
export { default as UiIcon } from './runtime/components/Icon.vue'
export { default as UiInput } from './runtime/components/Input.vue'
export { default as UiInputDate } from './runtime/components/InputDate.vue'
export { default as UiInputMenu } from './runtime/components/InputMenu.vue'
export { default as UiInputNumber } from './runtime/components/InputNumber.vue'
export { default as UiInputTags } from './runtime/components/InputTags.vue'
export { default as UiInputTime } from './runtime/components/InputTime.vue'
export { default as UiKbd } from './runtime/components/Kbd.vue'
export { default as UiLink } from './runtime/components/Link.vue'
export { default as UiLinkBase } from './runtime/components/LinkBase.vue'
export { default as UiMain } from './runtime/components/Main.vue'
export { default as UiMarquee } from './runtime/components/Marquee.vue'
export { default as UiModal } from './runtime/components/Modal.vue'
export { default as UiNavigationMenu } from './runtime/components/NavigationMenu.vue'
export { default as UiOverlayProvider } from './runtime/components/OverlayProvider.vue'
export { default as UiPage } from './runtime/components/Page.vue'
export { default as UiPageAnchors } from './runtime/components/PageAnchors.vue'
export { default as UiPageAside } from './runtime/components/PageAside.vue'
export { default as UiPageBody } from './runtime/components/PageBody.vue'
export { default as UiPageCTA } from './runtime/components/PageCTA.vue'
export { default as UiPageCard } from './runtime/components/PageCard.vue'
export { default as UiPageColumns } from './runtime/components/PageColumns.vue'
export { default as UiPageFeature } from './runtime/components/PageFeature.vue'
export { default as UiPageGrid } from './runtime/components/PageGrid.vue'
export { default as UiPageHeader } from './runtime/components/PageHeader.vue'
export { default as UiPageHero } from './runtime/components/PageHero.vue'
export { default as UiPageLinks } from './runtime/components/PageLinks.vue'
export { default as UiPageList } from './runtime/components/PageList.vue'
export { default as UiPageLogos } from './runtime/components/PageLogos.vue'
export { default as UiPageSection } from './runtime/components/PageSection.vue'
export { default as UiPagination } from './runtime/components/Pagination.vue'
export { default as UiPinInput } from './runtime/components/PinInput.vue'
export { default as UiPopover } from './runtime/components/Popover.vue'
export { default as UiPricingPlan } from './runtime/components/PricingPlan.vue'
export { default as UiPricingPlans } from './runtime/components/PricingPlans.vue'
export { default as UiPricingTable } from './runtime/components/PricingTable.vue'
export { default as UiProgress } from './runtime/components/Progress.vue'
export { default as UiRadioGroup } from './runtime/components/RadioGroup.vue'
export { default as UiSelect } from './runtime/components/Select.vue'
export { default as UiSelectMenu } from './runtime/components/SelectMenu.vue'
export { default as UiSeparator } from './runtime/components/Separator.vue'
export { default as UiSkeleton } from './runtime/components/Skeleton.vue'
export { default as UiSlideover } from './runtime/components/Slideover.vue'
export { default as UiSlider } from './runtime/components/Slider.vue'
export { default as UiStepper } from './runtime/components/Stepper.vue'
export { default as UiSwitch } from './runtime/components/Switch.vue'
export { default as UiTable } from './runtime/components/Table.vue'
export { default as UiTabs } from './runtime/components/Tabs.vue'
export { default as UiTextarea } from './runtime/components/Textarea.vue'
export { default as UiTimeline } from './runtime/components/Timeline.vue'
export { default as UiToast } from './runtime/components/Toast.vue'
export { default as UiToaster } from './runtime/components/Toaster.vue'
export { default as UiTooltip } from './runtime/components/Tooltip.vue'
export { default as UiTree } from './runtime/components/Tree.vue'
export { default as UiUser } from './runtime/components/User.vue'

// Utils
export { tv } from './runtime/utils/tv.js'
export * from './runtime/utils/index.js'

// Types
export type * from './runtime/types/index.js'
export type { ComponentConfig, AppConfig, TVConfig } from './runtime/types/tv.js'

// Theme exports (for customization)
export * as themes from './theme/index.js'
